// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaWo1gregPRLn1NTjotrk-xdPem5fBaoc',
    appId: '1:567009306845:web:1cc52327918749a5f39334',
    messagingSenderId: '567009306845',
    projectId: 'rick-and-morty-2c88e',
    authDomain: 'rick-and-morty-2c88e.firebaseapp.com',
    storageBucket: 'rick-and-morty-2c88e.firebasestorage.app',
    measurementId: 'G-XSMWC81BBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxpAZ1LITjC85P-tMTLZq8Jph6-6eH3oc',
    appId: '1:567009306845:android:df1fb89081b01343f39334',
    messagingSenderId: '567009306845',
    projectId: 'rick-and-morty-2c88e',
    storageBucket: 'rick-and-morty-2c88e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ1dK9i7tGvEakj1pgZOlyXLjUSOKdnTI',
    appId: '1:567009306845:ios:7db734fcdf41726ff39334',
    messagingSenderId: '567009306845',
    projectId: 'rick-and-morty-2c88e',
    storageBucket: 'rick-and-morty-2c88e.firebasestorage.app',
    iosBundleId: 'com.example.rickAndMorty',
  );
}
